### ISSUE TITLE
[Recommend HTTPS] https://letsencrypt.org/

### ISSUE THREAD

**Issue by JobsLong** [xtai/xtai.github.io#12]
A simple to way add https 🔒  for personal website or blog.

**Comment by xtai** [comment]
GitHub pages + cname custom domain 没办法用？现在 GitHub 的 CDN 挺快的感觉也没必要换

**Comment by xtai** [comment]
Possible solution:
- https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
- for apex domain: https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

These need to be evaluated:
- insecure resources, e.g. images of sinaimg.cn? (some browsers complain it, so it is a big no) [potential solution: ssl proxy?](http://stackoverflow.com/questions/765779/how-to-display-non-ssl-images-on-https-connection)
- GitHub Pages vs CloudFlare or what's CloudFlare's role here?
- how's CloudFlare? (looks good so far)
- encrypt sub-domains? (nah)
- redirects and page rules? e.g. https://xxxx.taixiaoyu.com/ -> https://taixiaoyu.com/xxxx/?
- cons of https (slow? certs renew? [pros and cons](https://blog.nexcess.net/2014/09/03/the-pros-and-cons-of-implementing-ssl-https/))
